# Generated by Django 5.0.6 on 2024-06-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='upload/')),
                ('upload_date', models.DateTimeField(auto_now=True)),
                ('download_count', models.IntegerField(blank=True, null=True)),
                ('email_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
