# Generated by Django 5.0.6 on 2024-06-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileServer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
