# Generated by Django 5.0.6 on 2024-06-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileServer', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
