# Generated by Django 5.0.6 on 2024-06-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileServer', '0002_file_image_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='email_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
