# Generated by Django 5.0.6 on 2024-06-17 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileServer', '0002_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
