# Generated by Django 5.0.6 on 2024-06-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileServer', '0003_alter_file_email_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
