# Generated by Django 5.0.6 on 2024-06-10 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileServer', '0005_category_file_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='category_id',
            new_name='category',
        ),
    ]
