# Generated by Django 5.0.6 on 2024-06-13 15:44

import fileServer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileServer', '0006_rename_category_id_file_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/', validators=[fileServer.models.validate_file_size]),
        ),
    ]
